name: IgeTickets Docker Image

on:
  push:
    branches: [ master ]
      
jobs:
  push_to_registry:
    name: Push Docker image to Github Packages
    runs-on: armhf

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build and Push the image to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v5.5
        with:
          image: igetickets
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          addLatest: true